#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation

index:
    path: /
    defaults: { _controller: 'App\Controller\PersonController::index' }

new:
    path: /Person/new
    defaults: { _controller: 'App\Controller\PersonController::newp' }

new2:
    path: /Material/new
    defaults: { _controller: 'App\Controller\MaterialController::newm' }

new3:
    path: /Inventory/new
    defaults: { _controller: 'App\Controller\InventoryController::newi' }

