#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation

index:
    path: /
    defaults: { _controller: 'App\Controller\PersonController::index' }

new:
    path: /new
    defaults: { _controller: 'App\Controller\PersonController::newp' }

